name: serverStatus client build

on:
  push:
    branchs:
      - main

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2 
        with:
          go-version: "1.16.5"

      - name: build
        working-directory: ./client
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o serverStatus-client_linux_amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o serverStatus-client_linux_arm64
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o serverStatus-client_darwin_amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o serverStatus-client_darwin_arm64
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            serverStatus-client_linux_amd64
            serverStatus-client_linux_arm64
            serverStatus-client_darwin_amd64
            serverStatus-client_darwin_arm64            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./client
